# =========================================================
# MI TEMA DE MIKUI PARA rEFInd
# =========================================================

# 1. Fondo de pantalla 
banner themes/miku-refind/fondo.png
banner_scale fillscreen

# 2. Carpeta base de los iconos
icons_dir themes/miku-refind/icons

# 3. Resolución de la pantalla
#resolution 1920 1080

# 4. Limpieza Extrema de la Interfaz
hideui label,singleuser,safemode,hwtest,arrows,hints,editor,badges

# 5. Tamaños de los Iconos
big_icon_size 128
small_icon_size 48

# 6. Indicador de Selección
selection_big themes/miku-refind/selection/puerro_big.png
selection_small themes/miku-refind/selection/puerro_small.png

# 7. Herramientas Inferiores
showtools shutdown,reboot,firmware