# =========================================================
# MI TEMA DE MIKUI PARA rEFInd
# =========================================================

# 1. Fondo de pantalla 
banner background.png

# 2. Carpeta base de los iconos
icons_dir icons

# 3. Resolución de la pantalla
resolution 1920 1080

# 4. Limpieza Extrema de la Interfaz
# Esto oculta los textos, consejos, flechas y etiquetas grises por defecto de rEFInd.
hideui label,singleuser,safemode,hwtest,arrows,hints,editor,badges

# 5. Tamaños de los Iconos (en píxeles)
# 'big' aplica a tus sistemas operativos (Windows/Linux)
# 'small' aplica a las herramientas de la parte inferior
big_icon_size 128
small_icon_size 48

# 6. Indicador de Selección
selection_big selection.png
selection_small selection.png

# 7. Herramientas Inferiores
showtools shutdown,reboot,firmware